/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const d: typeof import('@voerkai18n/core').d
  const n: typeof import('@voerkai18n/core').n
  const t: typeof import('@voerkai18n/core').t
  const tc: typeof import('@voerkai18n/core').tc
  const useI18n: typeof import('@voerkai18n/core').useI18n
}
